### ISSUE TITLE
Streamer List

### ISSUE THREAD

**Issue by geoffreyparrier** [Team-Sac/site#3]
# Add a simple Streamer List

## Required : 
- [x] Get Streamers from [Directus](directus.teamsac.xyz)
- [x] Show if they're on stream or not
- [x] Show name and profile picture
- [x] Show Streamers currently on stream on top
- [x] Add a button to hide this element
- [x] Add button to open this element

**Comment by YoanRouleau** [comment]
Marking some requirements as done.
